trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

stages:
  - template: azure-pipelines/build.yml
  - template: azure-pipelines/docker.yml
  - template: azure-pipelines/deploy.yml
  - template: azure-pipelines/smoke-test.yml