stages:
  - stage: Build
    displayName: Build, Test and SonarCloud Analysis

    jobs:
      - job: MavenBuild
        displayName: Maven Build and SonarCloud Scan

        pool:
          vmImage: ubuntu-latest

        steps:
          - checkout: self
            displayName: Checkout GitHub repository
            fetchDepth: 0

          - task: JavaToolInstaller@0
            displayName: Use Java 17
            inputs:
              versionSpec: '17'
              jdkArchitectureOption: x64
              jdkSourceOption: PreInstalled

          - task: SonarCloudPrepare@4
            displayName: Prepare SonarQube Cloud analysis
            inputs:
              SonarCloud: 'sc-sonarcloud-cloud'
              organization: 'kajalyadav-24'
              scannerMode: 'other'
              extraProperties: |
                sonar.projectKey=kajalyadav-24_azureshop-enterprise-devops
                sonar.projectName=azureshop-enterprise-devops
                sonar.projectBaseDir=application
                sonar.sources=src/main
                sonar.tests=src/test
                sonar.java.binaries=target/classes

          - task: Maven@4
            displayName: Maven clean package and SonarCloud analysis
            inputs:
              mavenPOMFile: 'application/pom.xml'
              goals: 'clean package'
              publishJUnitResults: true
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              javaHomeOption: Path
              jdkDirectory: '$(JAVA_HOME_17_X64)'
              sonarQubeRunAnalysis: true
              sqMavenPluginVersionChoice: 'latest'

          - task: SonarCloudPublish@4
            displayName: Publish SonarQube Cloud quality gate
            inputs:
              pollingTimeoutSec: '300'

          - task: PublishPipelineArtifact@1
            displayName: Publish application JAR
            inputs:
              targetPath: 'application/target'
              artifact: 'azureshop-jar'
              publishLocation: pipeline